[package]
name = "OtherEngine"
version = "0.1.0"
authors = ["yangdao <458424869@qq.com>"]
edition = "2018"

[dependencies]
qjs-rs = {path = "../qjs-rs"}
winit = "0.19.3"
glium = "*"

[profile.release]
opt-level = 'z'  # Optimize for size.
lto = true