[package]
name = "OtherEngine"
version = "0.1.0"
authors = ["yangdao <458424869@qq.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
qjs-rs = {path = "../qjs-rs"}
winit = "0.19.3"
glium = "*"